/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Password } from "./Password";
import { PasswordCountArgs } from "./PasswordCountArgs";
import { PasswordFindManyArgs } from "./PasswordFindManyArgs";
import { PasswordFindUniqueArgs } from "./PasswordFindUniqueArgs";
import { CreatePasswordArgs } from "./CreatePasswordArgs";
import { UpdatePasswordArgs } from "./UpdatePasswordArgs";
import { DeletePasswordArgs } from "./DeletePasswordArgs";
import { PasswordService } from "../password.service";
@graphql.Resolver(() => Password)
export class PasswordResolverBase {
  constructor(protected readonly service: PasswordService) {}

  async _passwordsMeta(
    @graphql.Args() args: PasswordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Password])
  async passwords(
    @graphql.Args() args: PasswordFindManyArgs
  ): Promise<Password[]> {
    return this.service.passwords(args);
  }

  @graphql.Query(() => Password, { nullable: true })
  async password(
    @graphql.Args() args: PasswordFindUniqueArgs
  ): Promise<Password | null> {
    const result = await this.service.password(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Password)
  async createPassword(
    @graphql.Args() args: CreatePasswordArgs
  ): Promise<Password> {
    return await this.service.createPassword({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Password)
  async updatePassword(
    @graphql.Args() args: UpdatePasswordArgs
  ): Promise<Password | null> {
    try {
      return await this.service.updatePassword({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Password)
  async deletePassword(
    @graphql.Args() args: DeletePasswordArgs
  ): Promise<Password | null> {
    try {
      return await this.service.deletePassword(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
