/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PasswordService } from "../password.service";
import { PasswordCreateInput } from "./PasswordCreateInput";
import { Password } from "./Password";
import { PasswordFindManyArgs } from "./PasswordFindManyArgs";
import { PasswordWhereUniqueInput } from "./PasswordWhereUniqueInput";
import { PasswordUpdateInput } from "./PasswordUpdateInput";

export class PasswordControllerBase {
  constructor(protected readonly service: PasswordService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Password })
  async createPassword(
    @common.Body() data: PasswordCreateInput
  ): Promise<Password> {
    return await this.service.createPassword({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        encrypted: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Password] })
  @ApiNestedQuery(PasswordFindManyArgs)
  async passwords(@common.Req() request: Request): Promise<Password[]> {
    const args = plainToClass(PasswordFindManyArgs, request.query);
    return this.service.passwords({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        encrypted: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Password })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async password(
    @common.Param() params: PasswordWhereUniqueInput
  ): Promise<Password | null> {
    const result = await this.service.password({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        password: true,
        encrypted: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Password })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePassword(
    @common.Param() params: PasswordWhereUniqueInput,
    @common.Body() data: PasswordUpdateInput
  ): Promise<Password | null> {
    try {
      return await this.service.updatePassword({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          encrypted: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Password })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePassword(
    @common.Param() params: PasswordWhereUniqueInput
  ): Promise<Password | null> {
    try {
      return await this.service.deletePassword({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          password: true,
          encrypted: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
